/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'fan' : IDL.Null,
  'gadgets' : IDL.Null,
  'kitchen' : IDL.Null,
  'health' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'commission' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'commission' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ResellerProfile = IDL.Record({
  'isApproved' : IDL.Bool,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'totalSales' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'affiliateCode' : IDL.Text,
  'registeredAt' : Timestamp,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'completed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'orderDate' : Timestamp,
  'productId' : ProductId,
  'commissionAmount' : IDL.Nat,
  'resellerPrincipal' : IDL.Principal,
});
export const Reseller = IDL.Record({
  'isApproved' : IDL.Bool,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'affiliateCode' : IDL.Text,
  'registeredAt' : Timestamp,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'productId' : ProductId,
  'resellerAffiliateCode' : IDL.Text,
});
export const ResellerInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyResellerProfile' : IDL.Func([], [IDL.Opt(ResellerProfile)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByReseller' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getResellerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ResellerProfile)],
      ['query'],
    ),
  'initSampleProducts' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listResellers' : IDL.Func([], [IDL.Vec(Reseller)], ['query']),
  'placeOrder' : IDL.Func([OrderInput], [Order], []),
  'registerReseller' : IDL.Func([ResellerInput], [Reseller], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [Product], []),
  'updateResellerStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'fan' : IDL.Null,
    'gadgets' : IDL.Null,
    'kitchen' : IDL.Null,
    'health' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'commission' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'commission' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ResellerProfile = IDL.Record({
    'isApproved' : IDL.Bool,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'totalSales' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'affiliateCode' : IDL.Text,
    'registeredAt' : Timestamp,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'orderDate' : Timestamp,
    'productId' : ProductId,
    'commissionAmount' : IDL.Nat,
    'resellerPrincipal' : IDL.Principal,
  });
  const Reseller = IDL.Record({
    'isApproved' : IDL.Bool,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'affiliateCode' : IDL.Text,
    'registeredAt' : Timestamp,
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'productId' : ProductId,
    'resellerAffiliateCode' : IDL.Text,
  });
  const ResellerInput = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyResellerProfile' : IDL.Func(
        [],
        [IDL.Opt(ResellerProfile)],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByReseller' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getResellerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ResellerProfile)],
        ['query'],
      ),
    'initSampleProducts' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listResellers' : IDL.Func([], [IDL.Vec(Reseller)], ['query']),
    'placeOrder' : IDL.Func([OrderInput], [Order], []),
    'registerReseller' : IDL.Func([ResellerInput], [Reseller], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [Product], []),
    'updateResellerStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };