/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'orderDate' : Timestamp,
  'productId' : ProductId,
  'commissionAmount' : bigint,
  'resellerPrincipal' : Principal,
}
export type OrderId = bigint;
export interface OrderInput {
  'customerName' : string,
  'customerPhone' : string,
  'productId' : ProductId,
  'resellerAffiliateCode' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'completed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'commission' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'fan' : null } |
  { 'gadgets' : null } |
  { 'kitchen' : null } |
  { 'health' : null };
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'commission' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'price' : bigint,
}
export interface Reseller {
  'isApproved' : boolean,
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'affiliateCode' : string,
  'registeredAt' : Timestamp,
}
export interface ResellerInput { 'name' : string, 'email' : string }
export interface ResellerProfile {
  'isApproved' : boolean,
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'totalSales' : bigint,
  'totalEarnings' : bigint,
  'affiliateCode' : string,
  'registeredAt' : Timestamp,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyResellerProfile' : ActorMethod<[], [] | [ResellerProfile]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByReseller' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getResellerProfile' : ActorMethod<[Principal], [] | [ResellerProfile]>,
  'initSampleProducts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'listResellers' : ActorMethod<[], Array<Reseller>>,
  'placeOrder' : ActorMethod<[OrderInput], Order>,
  'registerReseller' : ActorMethod<[ResellerInput], Reseller>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], Product>,
  'updateResellerStatus' : ActorMethod<[Principal, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];