/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    customerPhone: string;
    orderDate: Timestamp;
    productId: ProductId;
    commissionAmount: bigint;
    resellerPrincipal: Principal;
}
export interface ResellerProfile {
    isApproved: boolean;
    principal: Principal;
    name: string;
    email: string;
    totalSales: bigint;
    totalEarnings: bigint;
    affiliateCode: string;
    registeredAt: Timestamp;
}
export type Timestamp = bigint;
export interface ProductInput {
    name: string;
    description: string;
    commission: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    price: bigint;
}
export interface OrderInput {
    customerName: string;
    customerPhone: string;
    productId: ProductId;
    resellerAffiliateCode: string;
}
export interface ResellerInput {
    name: string;
    email: string;
}
export type ProductId = bigint;
export interface Reseller {
    isApproved: boolean;
    principal: Principal;
    name: string;
    email: string;
    affiliateCode: string;
    registeredAt: Timestamp;
}
export interface Product {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    commission: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    price: bigint;
}
export type OrderId = bigint;
export enum OrderStatus {
    pending = "pending",
    paid = "paid",
    completed = "completed"
}
export enum ProductCategory {
    fan = "fan",
    gadgets = "gadgets",
    kitchen = "kitchen",
    health = "health"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addProduct(input: ProductInput): Promise<Product>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteProduct(id: ProductId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getMyResellerProfile(): Promise<ResellerProfile | null>;
    getOrders(): Promise<Array<Order>>;
    getOrdersByReseller(): Promise<Array<Order>>;
    getProduct(id: ProductId): Promise<Product | null>;
    getResellerProfile(principal: Principal): Promise<ResellerProfile | null>;
    initSampleProducts(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listProducts(): Promise<Array<Product>>;
    listProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    listResellers(): Promise<Array<Reseller>>;
    placeOrder(input: OrderInput): Promise<Order>;
    registerReseller(input: ResellerInput): Promise<Reseller>;
    searchProducts(searchTerm: string): Promise<Array<Product>>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<void>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product>;
    updateResellerStatus(principal: Principal, approved: boolean): Promise<void>;
}
import type { Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, Product as _Product, ProductCategory as _ProductCategory, ProductId as _ProductId, ProductInput as _ProductInput, ResellerProfile as _ResellerProfile, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyResellerProfile(): Promise<ResellerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyResellerProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyResellerProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByReseller(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByReseller();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByReseller();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResellerProfile(arg0: Principal): Promise<ResellerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResellerProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResellerProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSampleProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleProducts();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByCategory(to_candid_ProductCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByCategory(to_candid_ProductCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResellers(): Promise<Array<Reseller>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResellers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResellers();
            return result;
        }
    }
    async placeOrder(arg0: OrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0);
                return from_candid_Order_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0);
            return from_candid_Order_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerReseller(arg0: ResellerInput): Promise<Reseller> {
        if (this.processError) {
            try {
                const result = await this.actor.registerReseller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerReseller(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResellerStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResellerStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResellerStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResellerProfile]): ResellerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    customerPhone: string;
    orderDate: _Timestamp;
    productId: _ProductId;
    commissionAmount: bigint;
    resellerPrincipal: Principal;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    customerPhone: string;
    orderDate: Timestamp;
    productId: ProductId;
    commissionAmount: bigint;
    resellerPrincipal: Principal;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        customerPhone: value.customerPhone,
        orderDate: value.orderDate,
        productId: value.productId,
        commissionAmount: value.commissionAmount,
        resellerPrincipal: value.resellerPrincipal
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    commission: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: _ProductCategory;
    price: bigint;
}): {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    commission: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        commission: value.commission,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: from_candid_ProductCategory_n7(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    completed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : "completed" in value ? OrderStatus.completed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fan: null;
} | {
    gadgets: null;
} | {
    kitchen: null;
} | {
    health: null;
}): ProductCategory {
    return "fan" in value ? ProductCategory.fan : "gadgets" in value ? ProductCategory.gadgets : "kitchen" in value ? ProductCategory.kitchen : "health" in value ? ProductCategory.health : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    commission: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: ProductCategory;
    price: bigint;
}): {
    name: string;
    description: string;
    commission: bigint;
    imageUrl: string;
    isFeatured: boolean;
    category: _ProductCategory;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        commission: value.commission,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: to_candid_ProductCategory_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    paid: null;
} | {
    completed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    fan: null;
} | {
    gadgets: null;
} | {
    kitchen: null;
} | {
    health: null;
} {
    return value == ProductCategory.fan ? {
        fan: null
    } : value == ProductCategory.gadgets ? {
        gadgets: null
    } : value == ProductCategory.kitchen ? {
        kitchen: null
    } : value == ProductCategory.health ? {
        health: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
